# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Flowchart.ui'
#
# Created: Mon Feb 16 11:58:15 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProcessFlow(object):
    def setupUi(self, ProcessFlow):
        ProcessFlow.setObjectName(_fromUtf8("ProcessFlow"))
        ProcessFlow.setEnabled(True)
        ProcessFlow.resize(996, 824)
        ProcessFlow.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        ProcessFlow.setFrameShape(QtGui.QFrame.StyledPanel)
        ProcessFlow.setFrameShadow(QtGui.QFrame.Raised)
        self.groupBox = QtGui.QGroupBox(ProcessFlow)
        self.groupBox.setGeometry(QtCore.QRect(170, 60, 651, 751))
        self.groupBox.setStyleSheet(_fromUtf8("font: 75 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);"))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 310, 481, 51))
        self.pushButton_10.setStyleSheet(_fromUtf8("color: rgb(170, 0,0);\n"
"font: 75 18pt \"Times New Roman\";\n"
""))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.line_6 = QtGui.QFrame(self.groupBox)
        self.line_6.setGeometry(QtCore.QRect(320, 540, 20, 31))
        self.line_6.setFrameShadow(QtGui.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_4 = QtGui.QFrame(self.groupBox)
        self.line_4.setGeometry(QtCore.QRect(320, 360, 20, 31))
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(90, 390, 481, 61))
        self.pushButton_11.setStyleSheet(_fromUtf8("color: rgb(170, 0,0);\n"
"font: 75 18pt \"Times New Roman\";\n"
""))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(160, 270, 20, 41))
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
##        self.pushButton_12 = QtGui.QPushButton(self.groupBox)
##        self.pushButton_12.setGeometry(QtCore.QRect(90, 480, 481, 61))
##        self.pushButton_12.setStyleSheet(_fromUtf8("color: rgb(170,0,0);\n"
##"font: 75 18pt \"Times New Roman\";\n"
##""))
##        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(160, 180, 20, 41))
        self.line_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.line_2.setStyleSheet(_fromUtf8(""))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(440, 180, 21, 131))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.pushButton_13 = QtGui.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(90, 480, 481, 61))
        self.pushButton_13.setStyleSheet(_fromUtf8("color: rgb(170, 0,0);\n"
"font: 75 18pt \"Times New Roman\";\n"
""))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.line_5 = QtGui.QFrame(self.groupBox)
        self.line_5.setGeometry(QtCore.QRect(320, 450, 20, 31))
        self.line_5.setFrameShadow(QtGui.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 220, 201, 51))
        self.pushButton_9.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
"font: 75 18pt \"Times New Roman\";\n"
"\n"
""))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(90, 120, 481, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_8.setPalette(palette)
        self.pushButton_8.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);\n"
"font: 75 18pt \"Times New Roman\";\n"
"\n"
""))
        self.pushButton_8.setAutoDefault(True)
        self.pushButton_8.setDefault(True)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.line_7 = QtGui.QFrame(self.groupBox)
        self.line_7.setGeometry(QtCore.QRect(320, 620, 21, 31))
        self.line_7.setFrameShadow(QtGui.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 50, 201, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);\n"
"font: 75 18pt \"Times New Roman\";\n"
"\n"
""))
        self.pushButton_2.setIconSize(QtCore.QSize(18, 16))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 40, 241, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);\n"
"font: 75 18pt \"Times New Roman\";\n"
""))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.line_8 = QtGui.QFrame(self.groupBox)
        self.line_8.setGeometry(QtCore.QRect(160, 90, 20, 31))
        self.line_8.setFrameShadow(QtGui.QFrame.Plain)
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
##        self.line_9 = QtGui.QFrame(self.groupBox)
##        self.line_9.setGeometry(QtCore.QRect(440, 90, 20, 31))
##        self.line_9.setFrameShadow(QtGui.QFrame.Plain)
##        self.line_9.setLineWidth(2)
##        self.line_9.setFrameShape(QtGui.QFrame.VLine)
##        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
##        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(90, 570, 481, 51))
        self.pushButton.setStyleSheet(_fromUtf8("color: rgb(170, 0,0);\n"
"font: 75 18pt \"Times New Roman\";\n"
""))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(ProcessFlow)
        self.label.setGeometry(QtCore.QRect(20, 680, 141, 101))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(ProcessFlow)
        self.label_2.setGeometry(QtCore.QRect(850, 700, 121, 81))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(ProcessFlow)
        self.label_3.setGeometry(QtCore.QRect(450, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(255, 85, 0);\n"
"font: 75 26pt \"Times New Roman\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton_4 = QtGui.QPushButton(ProcessFlow)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(880, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(_fromUtf8("color: rgb(0,170,255);"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.label_4 = QtGui.QLabel(ProcessFlow)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 151, 51))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton_5 = QtGui.QPushButton(ProcessFlow)
        self.pushButton_5.setGeometry(QtCore.QRect(880, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet(_fromUtf8("color: rgb(0, 170,255);"))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))

        self.retranslateUi(ProcessFlow)
        QtCore.QMetaObject.connectSlotsByName(ProcessFlow)

    def retranslateUi(self, ProcessFlow):
        ProcessFlow.setWindowTitle(_translate("ProcessFlow", "Trivim", None))
        self.pushButton_10.setText(_translate("ProcessFlow", "Point Cloud Generation", None))
        self.pushButton_11.setText(_translate("ProcessFlow", "Building Texture Extraction", None))
##        self.pushButton_12.setText(_translate("ProcessFlow", "Height Extraction", None))
        self.pushButton_13.setText(_translate("ProcessFlow", "3D-Model Generation", None))
        self.pushButton_9.setText(_translate("ProcessFlow", "Field Planning", None))
        self.pushButton_8.setText(_translate("ProcessFlow", "Camera Calibration", None))
        self.pushButton_2.setText(_translate("ProcessFlow", "New Project", None))
        self.pushButton_3.setText(_translate("ProcessFlow", "Load Project", None))
        self.pushButton.setText(_translate("ProcessFlow", "Database Query", None))
        self.label_3.setText(_translate("ProcessFlow", "Trivim", None))
        self.pushButton_4.setText(_translate("ProcessFlow", "Help", None))
        self.pushButton_5.setText(_translate("ProcessFlow", "About", None))

